Update packages/as-types/argument.ts documentation
massalabs/as pull request #131
Opened 2023-04-20 12:58 UTC by Elli610

2023-04-20 13:45 UTC, Ben-Rey requested changes

2023-04-20 13:45 UTC, Ben-Rey commented on packages/as-types/assembly/argument.ts
> +   * Initialize a new instance of Args.
Initializes was correct I think

2023-04-21 07:57 UTC, 0xSwapFeeder requested changes

2023-04-21 07:57 UTC, 0xSwapFeeder commented on packages/as-types/assembly/argument.ts
Missing @remarks in class description ?
Maybe use @link to talk about specific functions from the class also.

2023-04-21 07:57 UTC, 0xSwapFeeder commented on packages/as-types/assembly/argument.ts
> +   * @param serialized - The serialized arguments to pass to CallSC. Default: []
What is CallSC ?
I mean I might know, but Args is not only made for smart contract calls, this seems a bit out of context.

2023-04-21 07:57 UTC, 0xSwapFeeder commented on packages/as-types/assembly/argument.ts
> +   * @returns the serialized argument to pass to CallSC.
Same here with call SC

2023-04-21 07:57 UTC, 0xSwapFeeder commented on packages/as-types/assembly/argument.ts
> +   * This method deserializes an Ff2 from a serialized array starting from the current offset.
```suggestion
   * This method deserializes an F32 from a serialized array starting from the current offset.
```

2023-04-21 07:57 UTC, 0xSwapFeeder commented on packages/as-types/assembly/argument.ts
> +   * and returns it as a static array of unsigned 8-bit integers.
Maybe add a @remarks to explain that calling this function (unlike other 'next') doesn't increment the offset and therefore is quite usefull to fetch data directly and still be able to use other functions afterwards.
And also that using this function might produce duplicates of the data fetched for the same reasons.

2023-04-25 06:25 UTC, Ben-Rey requested changes
Some methods doesn't have title. It's repetitive but I would prefer to keep the style consistent.

2023-04-25 06:25 UTC, Ben-Rey commented on packages/as-types/assembly/argument.ts
> +   * This method deserializes a string from a serialized array starting from the current offset.
Same for the others, no need to repeat This method every time

2023-04-25 06:26 UTC, Ben-Rey commented on packages/as-types/assembly/argument.ts
> +   * @returns the serialized argument.
No tags in title, it will be weird in the generated doc

2023-04-25 09:28 UTC, 0xSwapFeeder approved these changes
@Ben-Rey lgtm

2023-04-25 10:48 UTC, Ben-Rey approved these changes

2023-04-25 12:29 UTC, merged