Update random.ts documentation
massalabs/as pull request #150
Opened 2023-04-21 09:10 UTC by Elli610

Closes #140

2023-04-21 12:32 UTC, Ben-Rey requested changes

2023-04-21 12:32 UTC, Ben-Rey commented on packages/as-proba/assembly/probability/random.ts
> + * Returns a non random secure number between given limits.
```suggestion
 * Returns an unsafe random integer between the given limits (inclusive).
```

2023-04-21 12:32 UTC, Ben-Rey commented on packages/as-proba/assembly/probability/random.ts
> + * @returns a non random secure number between given limits.
```suggestion
 * @returns an unsafe random integer between given limits.
```

2023-04-21 14:22 UTC, Ben-Rey approved these changes

2023-04-24 19:24 UTC, gregLibert approved these changes

2023-04-24 19:25 UTC, merged