docs(serializable-number): improved documentation
massalabs/as pull request #154
Opened 2023-04-21 12:04 UTC by 0xSwapFeeder

Aim's t resolve #144.

2023-04-21 12:37 UTC, windushka commented on packages/as-types/assembly/serialization/numbers.ts
>   * Convert a StaticArray<u8> to number
```suggestion
 * Converts a StaticArray<u8> to number
```

2023-04-21 12:37 UTC, windushka commented on packages/as-types/assembly/serialization/numbers.ts
> + * @typeParam T - the type of the number to convert (it must be an integer type)
```suggestion
 * @typeParam T - the type of the number to convert (it must be an integer type, such as i32, u32, i64, or u64)
```

2023-04-21 12:37 UTC, windushka commented on packages/as-types/assembly/serialization/numbers.ts
>  /**
It would be nice to include a short introductory comment at the beginning to provide a brief overview of the module's purpose.

2023-04-24 07:19 UTC, Elli610 requested changes
the @returns is not specified for bytesToI64

2023-04-24 07:19 UTC, Elli610 commented on packages/as-types/assembly/serialization/numbers.ts
>    if (!isInteger<T>()) {
it would be good to warn the reader of what happens if "isInteger<T>()" is false

2023-04-24 12:18 UTC, Ben-Rey requested changes

2023-04-24 13:15 UTC, merged