docs(as-types-strings): added remarks
massalabs/as pull request #157
Opened 2023-04-21 13:12 UTC by 0xSwapFeeder

Aim's to resolve #146.

2023-04-21 13:18 UTC, Elli610 approved these changes

2023-04-21 14:39 UTC, Ben-Rey requested changes

2023-04-21 14:39 UTC, Ben-Rey commented on packages/as-types/assembly/serialization/strings.ts
> + * @returns the converted StaticArray<u8>
```suggestion
 * @returns A StaticArray<u8> representation of the input string.
```

2023-04-21 14:39 UTC, Ben-Rey commented on packages/as-types/assembly/serialization/strings.ts
> + * @returns the converted string
```suggestion
 * @returns A UTF-16 string representation of the input array.
```

2023-04-21 14:39 UTC, Ben-Rey commented on packages/as-types/assembly/serialization/strings.ts
>   * Converts StaticArray<u8> to a string.
```suggestion
 * Converts a StaticArray<u8> containing UTF-8 encoded data to a UTF-16 string (AssemblyScript's default).
```

2023-04-21 14:39 UTC, Ben-Rey commented on packages/as-types/assembly/serialization/strings.ts
>   * Converts utf-16 string to a StaticArray<u8>.
```suggestion
 * Converts a UTF-16 string (AssemblyScript's default) to a UTF-8 encoded StaticArray<u8>.
```

2023-04-21 19:12 UTC, Ben-Rey approved these changes

2023-04-22 05:38 UTC, gregLibert approved these changes

2023-04-22 05:38 UTC, merged