Update combinatoric.ts
massalabs/as pull request #161
Opened 2023-04-21 14:20 UTC by Elli610

2023-04-21 16:40 UTC, 0xSwapFeeder requested changes

2023-04-21 16:40 UTC, 0xSwapFeeder commented on packages/as-proba/assembly/probability/combinatoric.ts
> + * @return
```suggestion

 * @return 
```

2023-04-21 16:40 UTC, 0xSwapFeeder commented on packages/as-proba/assembly/probability/combinatoric.ts
> + * @return
```suggestion

 * @return 
```

2023-04-21 16:40 UTC, 0xSwapFeeder commented on packages/as-proba/assembly/probability/combinatoric.ts
> + * @return The factorial of n.
```suggestion

 * @return The factorial of n.
```

2023-04-25 09:39 UTC, 0xSwapFeeder approved these changes
lgtm

2023-04-25 10:38 UTC, Ben-Rey approved these changes

2023-04-25 12:27 UTC, gregLibert approved these changes

2023-04-25 12:28 UTC, merged