Create CONTRIBUTING.md
massalabs/as pull request #180
Opened 2023-04-24 15:35 UTC by Elli610

closes #167

2023-04-25 08:54 UTC, Ben-Rey commented on packages/as-types/CONTRIBUTING.md
> +
```suggestion
```

2023-04-25 08:55 UTC, Ben-Rey approved these changes

2023-04-25 12:25 UTC, gregLibert requested changes

2023-04-25 12:25 UTC, gregLibert commented on packages/as-types/CONTRIBUTING.md
> +## Tests
We should tlak bout the fact this this is a mono repo and that the test and the CI should be started from the parent directory.
Maybe there is also other consideration to keep in mind that I'm not aware of

2023-04-26 14:12 UTC, gregLibert approved these changes

2023-04-26 14:14 UTC, merged