Create CONTRIBUTING.md for as-proba
massalabs/as pull request #184
Opened 2023-04-24 16:36 UTC by Elli610

2023-04-25 08:56 UTC, Ben-Rey commented on packages/as-proba/CONTRIBUTING.md
> +
```suggestion
```

2023-04-25 10:21 UTC, Ben-Rey approved these changes

2023-04-25 13:51 UTC, gregLibert requested changes

2023-04-25 13:51 UTC, gregLibert commented on packages/as-proba/CONTRIBUTING.md
> +## Tests
You should explain that you are in a mono repo

2023-04-25 15:34 UTC, gregLibert requested changes

2023-04-25 15:34 UTC, gregLibert commented on packages/as-proba/CONTRIBUTING.md
> +We are in a monorepo which contains 3 packages (as-types, as-transformer and as-proba). Inside each package is a folder /assembly/__tests__ which contains the test files related to the current packag
```suggestion
```

2023-04-25 15:34 UTC, gregLibert commented on packages/as-proba/CONTRIBUTING.md
> +```
```suggestion
However, please note that these package tests must also be run from the root of the monorepo when the CI executes npm run test to ensure the package works correctly in the larger context.
```

2023-04-26 14:13 UTC, gregLibert approved these changes

2023-04-26 14:13 UTC, merged