178 improve as transformer readme
massalabs/as pull request #188
Opened 2023-04-25 10:09 UTC by 0xSwapFeeder

Aim's to resolve #178.

2023-04-25 11:39 UTC, Elli610 requested changes
I am not sure about the code example. Did you test it ? 
( I didn't find anything about "create_sc". Did you mean createSC ? )

2023-04-25 13:36 UTC, Elli610 approved these changes

2023-04-26 11:17 UTC, Ben-Rey approved these changes

2023-04-26 14:15 UTC, gregLibert requested changes

2023-04-26 14:15 UTC, gregLibert commented on packages/as-transformer/README.md
> +
Don't you think that this should be in the contributing file.

2023-04-26 15:46 UTC, gregLibert approved these changes

2023-04-26 15:47 UTC, merged