Feature(as-types): improved SafeMath's assertions safety
massalabs/as pull request #216
Opened 2023-04-27 15:26 UTC by 0xSwapFeeder

Aim's to resolve #215 from meta #205.

2023-04-27 19:46 UTC, Ben-Rey approved these changes

2023-04-27 20:45 UTC, gregLibert requested changes

2023-04-27 20:45 UTC, gregLibert commented on packages/as-types/assembly/safeMath.ts
> +    assert(a + b >= 0, 'SafeMath: addition overflow');
useless, a and b are unsigned so by design this assertion will always be true

2023-04-27 20:45 UTC, gregLibert commented on packages/as-types/assembly/safeMath.ts
> +    assert(a + b <= u64.MAX_VALUE, 'SafeMath: addition overflow');
same as above, by design this is always true

2023-04-27 20:45 UTC, gregLibert commented on packages/as-types/assembly/safeMath.ts
> +    assert(a + b >= a, 'SafeMath: addition overflow');
This is the real assertion, but not well presented IMHO.
What you want is that:
a + b < u64.MAX_VALUE
<=> b < u64.MAX_VALUE - a (we substract by a on the left and on the right of the inequality as a >= 0)

So you assertiion should be :
b < u64.MAX_VALUE - a
```suggestion
    assert(b < u64.MAX_VALUE - a, 'SafeMath: addition overflow');
```

2023-04-27 20:45 UTC, gregLibert commented on packages/as-types/assembly/safeMath.ts
> +    if (a == 0 || b == 0) {
This update is useless: the check of the null value is not for performance, but to divide by a.

2023-04-27 20:45 UTC, gregLibert commented on packages/as-types/assembly/safeMath.ts
> +    assert((a * b) / a == b, 'SafeMath: multiplication overflow');
Can you correct this assertion using what I did for the previous one ?

2023-04-28 12:37 UTC, gregLibert commented on packages/as-types/assembly/safeMath.ts
> +    assert(b < u64.MAX_VALUE - a, 'SafeMath: addition overflow');
b = u64.MAX_VALUE and a = 0 shall pass
```suggestion
    assert(b <= u64.MAX_VALUE - a, 'SafeMath: addition overflow');
```

2023-05-02 11:19 UTC, gregLibert requested changes

2023-05-02 11:19 UTC, gregLibert commented on packages/as-types/assembly/safeMath.ts
> +    assert(b < u64.MAX_VALUE / a, 'SafeMath: multiplication overflow');
You start with:
a*b <= u.MAX
<=> b <= u.max/a, a > 0

```suggestion
    assert(b <= u64.MAX_VALUE / a, 'SafeMath: multiplication overflow');
```

2023-05-03 07:40 UTC, gregLibert approved these changes

2023-05-03 07:40 UTC, merged