Chore: updated dependencies
massalabs/as pull request #220
Opened 2023-04-27 15:45 UTC by 0xSwapFeeder

Aim's to resolve #219 from meta #205.

2023-04-28 06:57 UTC, Ben-Rey requested changes
Not sure about this. Test doesn't seem to work after update. L'et's talk about it

2023-04-29 10:02 UTC, Ben-Rey approved these changes

2023-04-29 10:05 UTC, Ben-Rey commented
@0xSwapFeeder don't you think the issue was talking about packages like "@massalabs/as-types": "^0.0.3**-dev**", ?

2023-05-04 19:43 UTC, Ben-Rey commented
> > @0xSwapFeeder don't you think the issue was talking about packages like "@massalabs/as-types": "^0.0.3**-dev**", ?
> > Not sure, could be it, but the issue name talks about dependencies, not package.json configuration for packages, or I didn't understood.

@gregLibert can you help us on this ?

2023-05-05 15:15 UTC, 0xSwapFeeder commented
Done ! @Ben-Rey

2023-05-18 08:05 UTC, Ben-Rey commented on packages/as-transformer/package.json
> +    "@massalabs/as-types": "^0.0.2",
```suggestion
    "@massalabs/as-types": "^1.0.0",
```

2023-05-19 11:26 UTC, Ben-Rey approved these changes

2023-05-19 21:12 UTC, Ben-Rey approved these changes

2023-05-19 22:23 UTC, merged