docs(as-transformer): added massaExport doc
massalabs/as pull request #226
Opened 2023-05-02 08:16 UTC by 0xSwapFeeder

Aim's to resolve #225 from meta #205

2023-05-02 11:44 UTC, Ben-Rey commented on packages/as-transformer/src/transformers/massaExport.ts
> + * The imports are the AS helpers generated by the protobuf files.
As I understand generateASHelpers, the helpers are generated by protoc from the proto files

2023-05-02 11:58 UTC, Ben-Rey commented on packages/as-transformer/src/helpers/protobuf.ts
> + *
Could be cool to have an short explaination of what is an helper in this context, why we need it.

2023-05-02 12:49 UTC, Ben-Rey approved these changes

2023-05-02 13:03 UTC, gregLibert requested changes

2023-05-02 13:03 UTC, gregLibert commented on packages/as-transformer/src/transformers/massaExport.ts
> + * It doesn't change the smart contract AST, it only generates the protobuf files and the AS helpers.
```suggestion
 * It doesn't change the smart contract AST, it only generates the protobuf files and the AS helpers in a build directory.
```

2023-05-03 07:39 UTC, gregLibert approved these changes

2023-05-03 07:39 UTC, merged