Fix: dependencies importing in protobuf transformer
massalabs/as pull request #242
Opened 2023-05-12 11:36 UTC by 0xSwapFeeder

2023-05-12 14:29 UTC, gregLibert requested changes

2023-05-12 14:29 UTC, gregLibert commented on packages/as-transformer/src/transformer.ts
> +          Array.from(neededImports.keys()).map((elem) => {
Why two array from ?

2023-05-12 14:29 UTC, gregLibert commented on packages/as-transformer/src/transformer.ts
> +            let splitted = elem.split('from ".');
should be a const instead of a let

2023-05-12 14:29 UTC, gregLibert commented on packages/as-transformer/src/transformer.ts
> +            if (splitted.length > 1 && splitted[1])
can you change your test on splitted[1] to something more explicite (not empty I guesss). Autocast is a nightmare and this part of the code is sufficiently complex.

2023-05-15 10:17 UTC, Ben-Rey approved these changes

2023-05-15 10:17 UTC, merged