Fix support for bignum array
massalabs/as pull request #337
Opened 2023-10-03 14:35 UTC by sydhds

2023-10-03 14:56 UTC, peterjah requested changes
a lot of code duplication.
I think it would have been possible to keep a generic templated function.
the byte buffer size of a class car be retrieved with `offsetof<T>()` 

You keeped `nextFixedSizeArray` but we now its not working with some types, maybe adding a check on types would be great to avoid futur bugs.

it would be also nice to complete/add unit tests that cover at least the bug you are fixing,

2023-10-04 08:02 UTC, sydhds commented
> a lot of code duplication. I think it would have been possible to keep a generic templated function. the byte buffer size of a class can be retrieved with `offsetof<T>()`
> 
> You keeped `nextFixedSizeArray` but we know its not working with some types, maybe adding a check on types would be great to avoid future bugs.
> 
> it would be also nice to complete/add unit tests that cover at least the bug you are fixing,

I've tried the generic function but the compiler rejects it. I've updated the code to use offsetof() and updated the unit tests as well.

2023-10-05 08:55 UTC, peterjah approved these changes

2023-10-05 09:03 UTC, sydhds reviewed
I would remove support for i256 as it is almost unimplemented in as-bignum...

2023-10-05 10:14 UTC, peterjah commented on packages/as-types/assembly/__tests__/argument.spec.ts
> -  it('With array of bytes', () => {
Yes i removed the support of serialize array of fixed size StaticArray... i don't see any usecase to this.
And its may be source of bug if the user provide elements of different sizes...

2023-10-05 10:15 UTC, peterjah commented on packages/as-types/assembly/serialization/bignum.ts
> +  return changetype<i128>(u128.from(wrapStaticArray(arr)));
i128 use same serialization of u128. its just the way we interprets the bytes that change

2023-10-06 07:48 UTC, merged